project:
  type: website

website:
  title: "Show Your Work - Tutorial"
  sidebar:
    style: "docked"
    logo: assets/logo.png
    favicon: assets/favicon.ico
    search: true
    contents:
      - section: "Getting Started"
        contents:
          - index.qmd
          - setup.qmd
      - introduction.qmd
      
      - concepts.qmd
      - title: "Slides"
        file: slides.qmd
      - links.qmd
      - libraries.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



