project:
  type: website

website:
  title: "Show Your Work - Tutorial"
  sidebar:
    style: "docked"
    logo: assets/logo.png
    favicon: assets/favicon.ico
    search: true
    contents:
      - section: "Getting Started"
        contents:
          - index.qmd
          - setup.qmd
      - section: "Core Concepts (coming soon)"
      - section: "Practical Examples (coming soon)"
      - section: "Best Practices (coming soon)"
      - section: "Reference (coming soon)"
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



