project:
  type: website

website:
  title: "Show Your Work - Tutorial"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Getting Started"
        contents:
          - index.qmd
          - installation.qmd
      - section: "Core Concepts"
        contents:
          - concepts/fundamentals.qmd
          - concepts/advanced.qmd
      - section: "Practical Examples"
        contents:
          - examples/basic-example.qmd
          - examples/complex-example.qmd
      - section: "Best Practices"
        contents:
          - best-practices/guidelines.qmd
          - best-practices/troubleshooting.qmd
      - section: "Reference"
        contents:
          - reference/api.qmd
          - reference/faq.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



