---
title: "Getting set up"
---

::: {.callout-note}
You are highly encouraged to run these steps before the tutorial. 
We will also set aside some time during the tutorial to get everyone set up.
:::

During this tutorial, we'll use **Quarto** to aggregate our apps (app store) and **HuggingFace Spaces** to deploy them. Please sign up for a HuggingFace account.

We will also review **Google Cloud Run** for hosting (optional). If you wish to follow along, please install `gcloud` CLI (optional).

- **Install Quarto:**  
    Follow the instructions at [quarto.org/docs/get-started](https://quarto.org/docs/get-started/).

- **Install Google Cloud CLI (optional):**  
    Follow the instructions at [cloud.google.com/sdk/docs/install](https://cloud.google.com/sdk/docs/install).

- **Create a HuggingFace account (optional):**  
    Go to [huggingface.co/new-space](https://huggingface.co/new-space).

- **Install tutorial files and install Python environment:**
    Install locally using the instructions below

::: {.callout-note}
### Setup Python environment locally

We'll required Python 3.9+ for this tutorial. You can download it [here](https://www.python.org/downloads/).

1. **Clone the Github repo and install dependencies**

```bash
git clone https://github.com/dkedar7/show_your_work
```

2. **Install dependencies**

Open the repo with your favorite text editor, create a virtual environment and install dependencies.

```bash
cd show_your_work
python -m venv .venv

source .venv/bin/activate # For Linux and MacOS
.venv\Scripts\activate # For Windows

pip install -r requirements.txt
```

3. **Add environment to Jupyter kernel list**

```bash
python -m ipykernel install --user --name="showyourwork"
```

4. **Launch Jupyter Lab to follow along**

```bash
jupyter lab
```
:::


### Test your setup

Launch a new Jupyter notebook, and run the following cell

```python
from fast_dash import fastdash

@fastdash
def simple_app(text: str):
    output_text = "This is my first Fast Dash app!"
    return output_text
```

::: {.callout-note}
If you have any questions or feedback, please email me at [kdabhadk@gmail.com](mailto:kdabhadk@gmail.com).
:::

